ens_jobeet_homepage:
  pattern:  /
  defaults: { _controller: EnsJobeetBundle:Job:index }


EnsJobeetBundle_end_job:
        resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
        prefix:   /job



