end_job:
    pattern:  /
    defaults: { _controller: "EnsJobeetBundle:Job:index" }

end_job_show:
    pattern:  /{id}/show
    defaults: { _controller: "EnsJobeetBundle:Job:show" }

end_job_new:
    pattern:  /new
    defaults: { _controller: "EnsJobeetBundle:Job:new" }

end_job_create:
    pattern:  /create
    defaults: { _controller: "EnsJobeetBundle:Job:create" }
    requirements: { _method: post }

end_job_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EnsJobeetBundle:Job:edit" }

end_job_update:
    pattern:  /{id}/update
    defaults: { _controller: "EnsJobeetBundle:Job:update" }
    requirements: { _method: post|put }

end_job_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EnsJobeetBundle:Job:delete" }
    requirements: { _method: post|delete }
